
[functions.send_email_from_queue]
enabled = true
verify_jwt = true
import_map = "./functions/send_email_from_queue/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send_email_from_queue/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send_email_from_queue/*.html" ]

[functions.send_email_engine]
enabled = true
verify_jwt = true
import_map = "./functions/send_email_engine/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send_email_engine/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send_email_engine/*.html" ]
